-d /home/mkhuthir/Downloads/fpga/tang_nano_9k/blink/blink/impl/gwsynthesis/blink.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /home/mkhuthir/Downloads/fpga/tang_nano_9k/blink/blink/src/blink.cst
-cfg /home/mkhuthir/Downloads/fpga/tang_nano_9k/blink/blink/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
